spring.application.name=Spring-sec-demo

spring.security.user.name=munna
spring.security.user.password=root

server.servlet.session.cookie.same-site=strict

spring.datasource.url=jdbc:postgresql://localhost:5432/hello
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update